# Generated by Django 4.2.4 on 2023-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topicmodel_m_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='unitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_char', models.CharField(max_length=20)),
            ],
        ),
    ]
