# Generated by Django 4.2.4 on 2023-09-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_unitsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='m_user',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='topic_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='topics.unitsmodel'),
        ),
    ]
