# Generated by Django 4.2.4 on 2023-09-07 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0004_remove_topicmodel_m_user_topicmodel_topic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='topic_unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='topics.unitsmodel'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='topic_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
