# Generated by Django 4.2.4 on 2023-09-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topicmodel_topic_unit_alter_topicmodel_topic_user'),
    ]

    operations = [
    ]
