# Generated by Django 4.2.4 on 2023-09-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_rename_m_name_topicmodel_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='m_name',
            new_name='topic_name',
        ),
    ]
