# Generated by Django 4.2.4 on 2023-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerconnectionsettingsmodel',
            name='broker_port',
            field=models.BigIntegerField(default=1883, max_length=10),
        ),
        migrations.AlterField(
            model_name='brokerconnectionsettingsmodel',
            name='broker_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
