# Generated by Django 4.2.4 on 2023-09-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_mqtttopicdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtttopicdata',
            name='mqtt_timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
